.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.md

Adds templates for the creation of issues in GitHub

Adds GitHub issue templates

---

src/docs/antora.yml
src/docs/modules/legal/nav.adoc
src/docs/modules/legal/pages/site-notice.adoc

This PR includes a section "Site Notice", which references all authors of the project, contains a link to the GitHub repository, contribution guideline and used license (MPL-2.0).

Integrate site notice section

---

.github/workflows/pull-request-check.yml

This commit introduces a GitHub Actions workflow that functions as a check for all pull requests. The workflow performs a normal build of the Antora documentation and fails if it does not succeed.

Include pull request check

---

README.md

* Add documentation and antora build badge

Add documentation and antora build badge (#22)

---

site.yml
src/docs/modules/ROOT/pages/namespaces.adoc

Updates namespace in BAMM referenced in the documentation.

---

.github/ISSUE_TEMPLATE/bug_report.md

This reverts commit 5c9965f4e9da4400c7104b7051305f0933af2357.
reverts accidentally commited changes to the bug issue template

Revert "Fix detail in Bug description"

---

gradle/wrapper/gradle-wrapper.properties

54-Update Gradle Wrapper

---

src/docs/modules/ROOT/pages/characteristics.adoc

51-Fix namespaces for lanuageCode and localeCode in spec

---

src/docs/modules/ROOT/examples/collection-with-element-characteristic.ttl
src/docs/modules/ROOT/examples/constrained-stringcode.ttl
src/docs/modules/ROOT/pages/modeling-guidelines.adoc

39-Fix incorrect constraint examples

---

src/docs/modules/ROOT/examples/aspect-sample.ttl

Fix namespaces in Either section of modeling guide

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Correction chapter title to include Traits

---

README.md

… to readme.md.
Signed-off-by: Johannes Kristan <johannes.kristan@bosch.io>
Fixes #37

Fix #37 Add explanation about the recursive nature of the BAMM acronym

---

src/main/resources/bamm/meta-model/1.0.0/aspect-meta-model-shapes.ttl
src/main/resources/bamm/meta-model/2.0.0/aspect-meta-model-shapes.ttl
src/test/java/io/openmanufacturing/sds/aspectmetamodel/AbstractShapeTest.java
src/test/java/io/openmanufacturing/sds/aspectmetamodel/CharacteristicShapeTest.java
src/test/java/io/openmanufacturing/sds/aspectmetamodel/EnumerationShapeTest.java
src/test/resources/bamm_1_0_0/characteristic-shape/io.openmanufacturing.test/1.0.0/TestCharacteristicInstanceWithCharacteristicAsDataType.ttl
src/test/resources/bamm_2_0_0/characteristic-shape/io.openmanufacturing.test/1.0.0/TestCharacteristicInstanceWithCharacteristicAsDataType.ttl

A Characteristic can no longer be used as a datatype.
fixes #73

Characteristic as datatype deemed invalid

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Remove broken link to non-existing section

---

.gitignore
src/docs/modules/ROOT/examples/payload-name-sample.ttl
src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Add description for `bamm:payloadName`.

---

src/docs/modules/appendix/pages/release-notes.adoc

Add missing release notes entry for namespace change

---

src/docs/modules/ROOT/examples/constrained-numberlist.ttl

Fix LengthConstraint example.

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc
src/docs/modules/ROOT/pages/payloads.adoc

Add Events to the Aspect specification.

---

site.yml
src/docs/modules/ROOT/pages/characteristics.adoc
src/docs/modules/ROOT/pages/entities.adoc

Include element URNs

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc
src/main/resources/bamm/meta-model/2.0.0/aspect-meta-model-shapes.ttl
src/test/java/io/openmanufacturing/sds/aspectmetamodel/AspectShapeTest.java
src/test/java/io/openmanufacturing/sds/aspectmetamodel/EntityShapeTest.java
src/test/resources/bamm_2_0_0/aspect-shape/io.openmanufacturing.test/1.0.0/TestAspectWithoutPropertiesAndOperations.ttl
src/test/resources/bamm_2_0_0/entity-shape/io.openmanufacturing.test/1.0.0/TestEntityWithoutProperties.ttl

Make presence of bamm:properties and bamm:operations optional

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc

OMP-BAMM-109: Clarify AbstractEntity inheritance.

---

src/docs/modules/ROOT/pages/payloads.adoc

OMP-BAMM-108: Fix payload mapping sample.

---

src/docs/modules/ROOT/pages/entities.adoc

Remove remainders of bamm:refines from documentation

---

src/docs/modules/ROOT/examples/localization-samples.ttl
src/docs/modules/ROOT/nav.adoc
src/docs/modules/ROOT/pages/localization.adoc
src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Extend the documentation to contain some notes on the localization possibilities.

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Fix broken formatting

---

src/main/resources/bamm/meta-model/2.0.0/type-conversions.ttl

Fix type conversion

---

src/docs/modules/ROOT/diagrams/aspect-meta-model.adoc

Rename "constraint" to "constraints" in meta model diagram

---

src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Remove reference to bamm:name

---

src/docs/modules/appendix/pages/release-notes.adoc

Update release notes for 2.0.0 release

---

src/docs/modules/ROOT/examples/aspect-sample.ttl
src/docs/modules/ROOT/examples/extending-entity-declaration-inheritance.ttl
src/docs/modules/ROOT/examples/multi-lang-example.ttl
src/docs/modules/ROOT/pages/modeling-guidelines.adoc

Fix validation for example models

---

.github/workflows/pull-request-check.yml

Run tests in PR build

---

src/main/resources/bamm/meta-model/1.0.0/aspect-meta-model-shapes.ttl
src/main/resources/bamm/meta-model/2.0.0/aspect-meta-model-shapes.ttl
src/test/java/io/openmanufacturing/sds/aspectmetamodel/PropertyShapeTest.java

Part of the fix for [#236](https://github.com/OpenManufacturingPlatform/sds-sdk/issues/236)

Remove cycle detection SHACL shape.

---

src/docs/modules/ROOT/examples/aspect-sample.ttl
src/docs/modules/ROOT/examples/either-declaration.ttl
src/docs/modules/ROOT/pages/modeling-guidelines.adoc
src/main/resources/bamm/meta-model/2.0.0/aspect-meta-model-shapes.ttl
src/test/java/io/openmanufacturing/sds/aspectmetamodel/AbstractPropertyShapeTest.java
src/test/java/io/openmanufacturing/sds/aspectmetamodel/AbstractShapeTest.java
src/test/java/io/openmanufacturing/sds/aspectmetamodel/AspectShapeTest.java
src/test/java/io/openmanufacturing/sds/aspectmetamodel/PropertyShapeTest.java
src/test/resources/bamm_2_0_0/abstract-property-shape/io.openmanufacturing.test/1.0.0/TestAbstractProperty.ttl
src/test/resources/bamm_2_0_0/abstract-property-shape/io.openmanufacturing.test/1.0.0/TestAbstractPropertyWithCharacteristic.ttl
src/test/resources/bamm_2_0_0/abstract-property-shape/io.openmanufacturing.test/1.0.0/TestAbstractPropertyWithExampleValue.ttl
src/test/resources/bamm_2_0_0/aspect-shape/io.openmanufacturing.test/1.0.0/TestAspectWithDoubleInstantiation.ttl
src/test/resources/bamm_2_0_0/property-shape/io.openmanufacturing.test/1.0.0/TestProperty.ttl
src/test/resources/bamm_2_0_0/property-shape/io.openmanufacturing.test/1.0.0/TestPropertyWithInvalidScalarExampleValue.ttl

Fixes #173. This PR adds SHACL shapes for structures that are described in the
textual spec but were not properly checked/validated before.

Improve/augment SHACL shapes

---

src/main/resources/bamm/characteristic/2.0.0/characteristic-shapes.ttl
src/main/resources/bamm/meta-model/2.0.0/aspect-meta-model-shapes.ttl

Add hints for error formatting.

---

README.md
documentation/modules/ROOT/examples/model-evolution2.ttl
documentation/modules/ROOT/examples/model-evolution3.ttl
documentation/modules/ROOT/examples/model-evolution4.ttl
documentation/modules/ROOT/examples/model-evolution5.ttl
documentation/modules/ROOT/pages/characteristics.adoc
documentation/modules/ROOT/pages/datatypes.adoc
documentation/modules/ROOT/pages/entities.adoc
documentation/modules/ROOT/pages/index.adoc
documentation/modules/ROOT/pages/limits.adoc
documentation/modules/ROOT/pages/meta-model-elements.adoc
documentation/modules/ROOT/pages/modeling-guidelines.adoc
documentation/modules/ROOT/pages/payloads.adoc
documentation/modules/appendix/nav.adoc
documentation/modules/appendix/pages/best-practices.adoc
documentation/modules/appendix/pages/model-evolution.adoc

Add section on model evolution

---

documentation/modules/ROOT/pages/modeling-guidelines.adoc

Changes:
- update docs for naming convention of Events.

fix: Define naming convention for Events

---

CONTRIBUTING.md

Update contribution guidelines after ESMF migration

---

.github/workflows/pull-request-check.yml
CONTRIBUTING.md
documentation/decisions/0000-use-markdown-any-decision-records.md
documentation/decisions/README.md
documentation/decisions/adr-template.md

Introduce Architecture Decision Records

---

.github/workflows/pull-request-check.yml

This hopefully unstucks PR checks that make only changes to the MADRs (see e.g., #243).

Fix PR check job

---

.github/workflows/pull-request-check.yml
documentation/decisions/0001-formalism-for-aspect-models.md
documentation/decisions/0002-aspect-model-file-extension.md
documentation/decisions/0003-meta-model-specification.md
documentation/decisions/0004-urn-as-identifiers.md
documentation/decisions/0005-rdf-vocabulary.md
documentation/decisions/0006-unit-catalog.md

Describe important past design decisions

---

documentation/modules/ROOT/pages/characteristics.adoc
documentation/modules/ROOT/pages/datatypes.adoc
documentation/modules/ROOT/pages/meta-model-elements.adoc
documentation/modules/ROOT/pages/modeling-guidelines.adoc
documentation/modules/ROOT/pages/namespaces.adoc
documentation/modules/appendix/pages/model-evolution.adoc

Review terms for "should"/"must" actions for RBS docs & SAMM spec 

---

esmf-semantic-aspect-meta-model/src/main/resources/samm/meta-model/2.2.0/aspect-meta-model-shapes.ttl
esmf-semantic-aspect-meta-model/src/test/java/org/eclipse/esmf/samm/AbstractShapeTest.java
esmf-semantic-aspect-meta-model/src/test/java/org/eclipse/esmf/samm/ConstraintShapeTest.java
esmf-semantic-aspect-meta-model/src/test/java/org/eclipse/esmf/samm/ConstraintSubClassCoreTest.java
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/constraint-shape/org.eclipse.esmf.test/1.0.0/TestConstraintWithoutProperties.ttl
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/constraint-subclass-core/org.eclipse.esmf.test/1.0.0/TestConstraint.ttl
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/constraint-subclass-core/org.eclipse.esmf.test/1.0.0/TestConstraintNonUniqueLangStrings.ttl
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/constraint-subclass-core/org.eclipse.esmf.test/1.0.0/TestConstraintWithDataType.ttl
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/constraint-subclass-core/org.eclipse.esmf.test/1.0.0/TestConstraintWithEmptyProperties.ttl
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/constraint-subclass-core/org.eclipse.esmf.test/1.0.0/TestConstraintWithInvalidLangStrings.ttl

Changes:
- add validation of empty Constraint;
- add tests.
Fixes: #274

Model with '... samm:Constraint.' statements is valid.

---

documentation/modules/ROOT/pages/characteristics.adoc

Changes:
- update documentation for length constraint.
Fixes: #267

Model with contradicting Constraint

---

documentation/modules/appendix/pages/best-practices.adoc

Add best practice for using metric units

---

documentation/modules/ROOT/pages/datatypes.adoc

Add missing minus sign

---

documentation/modules/appendix/pages/best-practices.adoc

Changes:
- add reuse best practice;
- add strict ttl best practice.

Make reuse best practice

---

.github/workflows/pull-request-check.yml
CONTRIBUTING.md
README.md

-------
Remove reference to ESMF forum.
Fixes #310.

Remove reference to ESMF forum

---

documentation/modules/ROOT/examples/aspect-sample.ttl

-------
Update usage example for `samm-c:TimeSeries` to properly use `samm-e:value`.
Fixes #313

Fix time series example in modeling guidelines

---

documentation/antora.yml
documentation/modules/appendix/nav.adoc
documentation/modules/release-notes/nav.adoc
documentation/modules/release-notes/pages/release-notes.adoc

Documentation: move Release Notes one level up.
Fixes #317 

Documentation: move Release Notes one level up

---

documentation/modules/ROOT/examples/aspect-sample.ttl
documentation/modules/ROOT/pages/entities.adoc
documentation/modules/ROOT/pages/modeling-guidelines.adoc
esmf-semantic-aspect-meta-model/src/main/resources/samm/entity/2.2.0/Quantity.ttl
esmf-semantic-aspect-meta-model/src/test/java/org/eclipse/esmf/samm/AbstractShapeTest.java
esmf-semantic-aspect-meta-model/src/test/java/org/eclipse/esmf/samm/QuantityTest.java
esmf-semantic-aspect-meta-model/src/test/resources/samm_2_2_0/quantity/org.eclipse.esmf.test/1.0.0/QuantityTestEntity.ttl

Express the relationship between a "value" Property and corresponding "unit reference" property. Add documentation
Fixes #316 

Express relationship between a "value" Property and corresponding "unit reference" property

---

documentation/modules/ROOT/pages/namespaces.adoc

-------
Fixes #275
- Update documentation with explicit description
Add any other notes or comments here.

Clarify usage of `xsd` and `rdfs` RDF prefixes

---

documentation/modules/ROOT/examples/aspect-sample.ttl
documentation/modules/ROOT/pages/modeling-guidelines.adoc

Add explanation on how to use samm:see when referencing IRDIs.
Fixes #320

Explain samm:see usage with IRDIs

---

documentation/modules/ROOT/pages/modeling-guidelines.adoc

Fixes #303
- [-] I have made corresponding changes to the documentation

Fix section formatting

---

documentation/modules/ROOT/examples/abstract-property-sample.ttl
documentation/modules/ROOT/examples/aspect-sample.ttl
documentation/modules/ROOT/examples/aspect-with-double-either-characteristic.ttl
documentation/modules/ROOT/examples/collection-with-element-characteristic.ttl
documentation/modules/ROOT/examples/constrained-numberlist.ttl
documentation/modules/ROOT/examples/constrained-stringcode.ttl
documentation/modules/ROOT/examples/either-declaration.ttl
documentation/modules/ROOT/examples/extending-entity-declaration-inheritance.ttl
documentation/modules/ROOT/examples/inline-numberlist.ttl
documentation/modules/ROOT/examples/localization-samples.ttl
documentation/modules/ROOT/examples/model-evolution.ttl
documentation/modules/ROOT/examples/model-evolution2.ttl
documentation/modules/ROOT/examples/model-evolution3.ttl
documentation/modules/ROOT/examples/model-evolution4.ttl
documentation/modules/ROOT/examples/model-evolution5.ttl
documentation/modules/ROOT/examples/multi-lang-example.ttl
documentation/modules/ROOT/examples/optional-properties-sample.ttl
documentation/modules/ROOT/examples/payload-name-sample.ttl
documentation/modules/ROOT/examples/prefixes-sample.ttl
documentation/modules/ROOT/examples/regular-numberlist.ttl
documentation/modules/ROOT/examples/structured-value-sample.ttl
documentation/modules/ROOT/examples/unit-reference.ttl
documentation/modules/ROOT/pages/modeling-guidelines.adoc

Remove duplicate element definitions in aspect-sample.ttl (that are invalid and
therefore break the build), and update the prefixes in the example models.

Fix sample model and update test models

---

documentation/modules/appendix/pages/best-practices.adoc

-------
Clarify usage of model element names
Fixes #331

Clarify terminology for "name" attribute in best practices

---

.github/workflows/pull-request-check.yml
.github/workflows/release-artifact.yml
esmf-semantic-aspect-meta-model/src/main/java/org/eclipse/esmf/samm/KnownVersion.java

Was updated KnownVersion enum. 
Fixes #338 

Improve performance

---

documentation/decisions/0007-model-resolution.md

Add a restriction point to the model resolving section.
Fixes #790
-  [x] Clarification in documentation
- [-] I have made corresponding changes to the documentation

Add a restriction point
